### PR TITLE
Use due credit to point to the relevant citation

### PR DESCRIPTION
**Pull request by arokem**
This is a low-cost way to give credit to the relevant publications. This will
only express itself, if the user runs it with duecredit. But when that happens,
we'll be ready!

Am I doing this right, @yarikoptic?

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thanks @arokem !  It points to something I forgot about for the due.py stub -- PEP8 compliance!  shame on me.... will fix up within an hour or so, will send you a PR and will fix up your little PEP8 gotchas.

**Comment by arokem** [comment]
Am I doing it right otherwise? Will this somehow automagically pull the citation from that DOI? And then when someone runs a script that uses shablona (with `-m duecredit`) they will be notified about this reference?

**Comment by yarikoptic** [comment]
On Tue, 19 Apr 2016, Ariel Rokem wrote:

>    Am I doing it right otherwise? Will this somehow automagically pull the
>    citation from that DOI? And then when someone runs a script that uses
>    shablona (with -m duecredit) they will be notified about this reference?

yes that is how it should work but few minor tune ups are needed
apparently:

$> python -m duecredit /usr/bin/nosetests shablona 
2016-04-19 11:34:49,670 [WARNING] DueCredit internal failure while running <function cite at 0x7f702cc09d70>: ValueError('path must be provided',). Please report to developers at https://github.com/duecredit/duecredit/issues (utils.py:76)
....

So with this change:

-due.cite(Doi("10.1167/13.9.30"))
+due.cite(Doi("10.1167/13.9.30"),
-         description="Template project for small scientific Python projects",
-         path='shablona')

it looks like (yet to figure out why **version**) wasn't picked up

$> python -m duecredit /usr/bin/nosetests shablona

## .....

Ran 5 tests in 0.024s

OK

DueCredit Report:
- Scientific tools library / numpy (v 1.11b3) [1]
- Data analysis library for tabular data / pandas (v 0.17.1) [2]
- Scientific tools library / scipy (v 0.17) [3]
- Template project for small scientific Python projects / shablona (v UNKNOWN) [4]

4 packages cited
0 modules cited
0 functions cited

## References

[1] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.
[2] McKinney, 2010.  Data Structures for Statistical Computing in Python . In S. van der Walt & Millman, eds.  Proceedings of the 9th Python in Science Conference . pp. 51–56.
[3] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.
[4] Rokem, A. & Landau, A., 2013. Orientation-specific surround suppression is not alleviated by voluntary attention. Journal of Vision, 13(9), pp.30–30.

I will make sure it works (got behind time so had to switch to other
things, but will send a PR later today), cheers!

## 

Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
FWIW -- pushed as a PR against your original branch so whenever you merge it it should appear here (apparently you haven't enabled travis for your own clone so tests were not ran)

**Comment by yarikoptic** [comment]
BTW why appveyor doesn't report, I thought you had it enabled?

**Comment by arokem** [comment]
Ugh. Appveyor is the worst. I just updated the webhook. Let's see if that does the thing. I will also need to write an explanation in the README...

**Comment by arokem** [comment]
Still need to do: 
- [x] Explain what this is (in the README)
- [ ] Test?

**Comment by arokem** [comment]
I think this is ready to go. Merging.

**Pull request merged**
