### PR TITLE
Remove automatically generated files from doc/reference.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
@andim: Does this look about right?

**Comment by andim** [comment]
There seems to be a further issue, which is that right now in the Makefile only html is dependent on the api reference generation, whereas all the other output formats also need it. This could be fixed in the Makefile.

More severly: If you handle the dependency via the Makefile I run into trouble with readthedocs as it does not know that it should generate the references!

Therefore a probably nicer way to handle the api reference generation is to let it be generated directly from conf.py. I hacked together such a solution in andim/noisyopt@13541ac. Comments welcome :)

**Comment by arokem** [comment]
Would you mind making a PR with this?

**Comment by andim** [comment]
Sure, see PR #28

**Comment by arokem** [comment]
Now, with #28 merged, is it a good time to merge this one as well?

**Comment by andim** [comment]
I don't see why not!

**Comment by arokem** [comment]
Thanks!

**Pull request merged**
