### PR TITLE
Add CI on Windows with appveyor.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by jakevdp** [comment]
Nice! Great to have a template for this – did you enable appveyor in the repo settings? It would be nice to see it run on this branch to confirm that everything is set up correctly :smile:

**Comment by arokem** [comment]
Thanks for the reminder! For now, I've activated it on my fork. We'll see
that it completes cleanly there, and then we can also activate it here (I
think).

**Comment by arokem** [comment]
OK. With a bit of trial and error, I think that I've figured this one out. Ready to flip the switch over here as well!

**Comment by arokem** [comment]
OK - that's all set. For future reference this is a bit tricky: needs to be done on the appveyor site by going to the project, choosing the "settings " tab and changing the url. For example, in this case, I had to change from "arokem/shablona" to "uwescience/shablona". But once I did that, appveyor appeared as a check on this page as well.

**Pull request merged**
